#!/usr/bin/python3
import py_compile
import os
if 'PYFILE' in os.environ:
    py_file = os.environ['PYFILE']
    pyc_file = py_file + 'c'
    py_compile.compile(py_file, cfile=pyc_file)
    print(f'Compiling {py_file} ...')
else:
    print("PYFILE environment variable is not set.")
